### ISSUE TITLE
모의면접 질문 도메인 서비스 구조 개선

### ISSUE THREAD

**Issue by Jang990** [Jang990/MockInterview#17]
## Description
- #8 하위 이슈

## To-do
- [x] InterviewInfo 검색을 인프라 -> 애플리케이션 계층으로 바꾸기
- [x] InterviewProgress 인프라 -> 애플리케이션 계층으로 바꾸기
- [x] 도메인 계층 인터페이스 구현체에서 Repository 제거하기.
- [x] QuestionRecommender가 단순히 추천할 질문 ID를 반환하도록 수정
- [x] AI 질문 생성기가 질문 String을 반환하도록 수정
