### ISSUE TITLE
부족한 기능 수정

### ISSUE THREAD

**Issue by Jang990** [Jang990/MockInterview#27]
## Description
부족한 기능 수정

## To-do
- [x] 내 질문 페이지 링크 수정
- [x] 카테고리 페이지 제거
- [x] 좋아하는 질문 기능 추가
