### ISSUE TITLE
면접 생성자를 테스트하기 쉽게 리팩토링

### ISSUE THREAD

**Issue by Jang990** [Jang990/MockInterview#49]
## Description
면접 생성자를 테스트하기 쉽게 리팩토링

## To-do
- [x] 면접 토픽(기술 주제, 경험 주제)을 생성해서 면접 생성자에 넘기도록 변경
- [x] 면접을 생성하면 주제를 변경할 수 없게 lineTech 등등의 메서드들을 없앨 것
- [x] 면접 타이머를 생성해서 면접 생성자에 넘기도록 변경
- [x] 면접 지원자 정보(users, 카테고리, 포지션)를 생성해서 면접 생성자에 넘기도록 변경
